<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Customer Loan Statement - {{ $reportData['loan_no'] }}</title>
    <style>
        @page {
            size: A4 landscape;
            margin: 10mm;
        }

        body {
            font-family: Calibri, Arial, Helvetica, sans-serif;
            font-size: 11px;
            color: #000;
            margin: 0;
            padding: 0;
        }

        .pdf-page-container,
        .container {
            width: 100%;
            padding: 4mm 3mm;
            box-sizing: border-box;
        }

        hr {
            border: none;
            border-top: 2px solid #3b82f6;
            margin: 8px 0 12px;
        }

        @include('loans.reports.partials.pdf_company_header_styles')

        .meta-box table {
            width: 100%;
            border-collapse: collapse;
            font-size: 9px;
            margin-bottom: 10px;
        }

        .meta-box td {
            border: 1px solid #cbd5e1;
            padding: 3px 5px;
        }

        .meta-box td:nth-child(even) {
            text-align: right;
        }

        .meta-box strong {
            color: #1e40af;
        }

        .statement-sheet {
            width: 100%;
        }

        .statement-table {
            width: 100%;
            border-collapse: collapse;
            font-family: Calibri, Arial, sans-serif;
            font-size: 10px;
            color: #000;
        }

        .statement-table td,
        .statement-table th {
            border: 1px solid #000;
            padding: 3px 5px;
            vertical-align: middle;
        }

        .client-name-cell {
            text-align: center;
            font-weight: 700;
            font-size: 12px;
            border: none !important;
            padding-bottom: 8px;
        }

        .summary-label {
            font-weight: 700;
            background: #f3f4f6;
        }

        .schedule-head th {
            background: #fff;
            font-weight: 700;
            text-align: center;
            font-size: 9px;
        }

        .amount {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .fee-remarks-paid {
            background: #92d050 !important;
            color: #000;
            font-weight: 600;
            text-align: center;
        }

        .fee-remarks-unpaid {
            background: #ff0000 !important;
            color: #fff;
            font-weight: 600;
            text-align: center;
        }

        .outstanding-paid {
            background: #92d050 !important;
        }

        .outstanding-overdue {
            background: #ff0000 !important;
            color: #fff;
            font-weight: 600;
        }

        .totals-row td {
            background: #f9fafb;
            font-weight: 700;
        }

        .settlements-header {
            background: #4472c4 !important;
            color: #fff;
            font-weight: 700;
            text-align: center;
        }

        .settlement-outstanding {
            background: #ff0000 !important;
            color: #fff;
            font-weight: 700;
        }

        .settlement-loan {
            background: #ffff00 !important;
            color: #000;
            font-weight: 700;
        }

        .settlement-label {
            font-weight: 700;
        }

        .footer-note {
            margin-top: 8px;
            font-size: 9px;
            text-align: center;
            color: #555;
        }
    </style>
</head>
<body>
    <div class="container pdf-page-container">
        @include('loans.reports.partials.pdf_company_header', [
            'company' => $company,
            'reportTitle' => 'Customer Loan Statement',
        ])

        {{-- Report meta --}}
        <div class="meta-box">
            <table>
                <tr>
                    <td><strong>Loan No:</strong></td>
                    <td>{{ $reportData['loan_no'] }}</td>
                    <td><strong>As of Date:</strong></td>
                    <td>{{ \Carbon\Carbon::parse($asOfDate)->format('d F Y') }}</td>
                    <td><strong>Branch:</strong></td>
                    <td>{{ $branch->name ?? $reportData['branch_name'] ?? 'N/A' }}</td>
                </tr>
                <tr>
                    <td><strong>Product:</strong></td>
                    <td>{{ $reportData['product_name'] }}</td>
                    <td><strong>Generated:</strong></td>
                    <td>{{ now()->format('d/m/Y H:i') }}</td>
                    <td><strong>Generated By:</strong></td>
                    <td>{{ $user->name ?? 'System' }}</td>
                </tr>
            </table>
        </div>

        {{-- Statement body (same as view page) --}}
        <div class="statement-sheet">
            @include('loans.reports.partials.customer_loan_statement_sheet', ['reportData' => $reportData])
        </div>

        <div class="footer-note">
            Loan No: {{ $reportData['loan_no'] }} | Statement as of {{ \Carbon\Carbon::parse($asOfDate)->format('d F Y') }}
        </div>
    </div>
</body>
</html>
